### ISSUE TITLE
A question for some parameters

### ISSUE THREAD

**Issue by Fengjiahao2** [ankargren/mfbvar#2]
Thx a lot for your contribution to the mixed-frequency var model.
I have two questions: 1) how to decide the number of lags? 2) how to decide the matrix entered in the "prior_intervals"

**Comment by ankargren** [comment]
1) You can either look at residuals and pick a lag length which makes them uncorrelated, or if you’re doing prediction you can use part of your data set as a test set and see which lag length works better. Of course, there is a vast array of approaches for lag length selection in the literature (information criteria etc), but these two are common. Because the models are using Bayesian shrinkage (which more heavily penalizes coefficients on higher-order lags) it generally works OK to pick a large lag length (to sort of be on the safe side).

For 2), that is entirely subjective. You only need this for the steady state prior, for which the original paper by Villani (2009) is a good start. There is no universal answer, but you will need to elicit a prior based on your beliefs.
